name = "EmpirikosBNP"
uuid = "ea739e02-4d30-4a0b-9098-9554a276d33c"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Empirikos = "cab608d6-c565-4ea1-96d6-ce5441ba21b0"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Empirikos = "0.6.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
